# Cloud Build configuration file
# This defines the steps Cloud Build will execute to build, push, and deploy the application

# Substitution variables
# These can be passed from the command line or GitHub Actions
# Default values are provided for local testing
substitutions:
  _REGION: asia-east1
  _APP_NAME: gcp-devops-demo

# Build steps executed in order
steps:
  # Step 1: Build the Docker image
  # Uses Docker's BuildKit for faster builds and better caching
  - name: 'gcr.io/cloud-builders/docker'
    id: build-image
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}-repo/${_APP_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}-repo/${_APP_NAME}:latest'
      - './app'  # Build context (directory containing Dockerfile)
    env:
      - 'DOCKER_BUILDKIT=1'
  
  # Step 2: Push the Docker image to Artifact Registry
  # Pushes both the commit SHA tag and the 'latest' tag
  - name: 'gcr.io/cloud-builders/docker'
    id: push-image
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}-repo/${_APP_NAME}'
    waitFor: ['build-image']  # Wait for build to complete
  
  # Step 3: Deploy the image to Cloud Run
  # This updates the Cloud Run service with the new image
  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-cloud-run
    args:
      - 'run'
      - 'deploy'
      - '${_APP_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}-repo/${_APP_NAME}:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'  # Allow public access
      - '--set-env-vars=VERSION=1.0.0,ENVIRONMENT=production'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'  # Scale to zero when no traffic
      - '--max-instances=10'
      - '--port=8080'
      - '--timeout=300'  # Request timeout (5 minutes)
    waitFor: ['push-image']  # Wait for push to complete

# Images to be pushed to Artifact Registry
# Cloud Build will push these automatically after the build completes
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}-repo/${_APP_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}-repo/${_APP_NAME}:latest'

# Build configuration options
options:
  # Use a more powerful machine for faster builds
  machineType: 'E2_HIGHCPU_8'
  
  # Logging configuration
  logging: CLOUD_LOGGING_ONLY
  
  # Build timeout (default is 10 minutes)
  #timeout: '1200s'  # 20 minutes

# Build timeout (maximum time for the entire build)
timeout: '1200s'
